baseURL: https://mastergroosha.github.io/
languageCode: ru-RU
title: –ì—Ä—É—à–∞ üçê
theme: PaperMod

params:
    env: production
    title: "–î–æ–º–∞—à–Ω—è—è —Å—Ç—Ä–∞–Ω–∏—Ü–∞ –ì—Ä—É—à–∏"
    description: "–û–±–æ –º–Ω–µ –∏ –º–æ–∏—Ö –ø—Ä–æ–µ–∫—Ç–∞—Ö"
    author:

    defaultTheme: auto

    mainSections:
        - posts

    profileMode:
        enabled: false

    socialIcons:
        - name: github
          url: "https://github.com/MasterGroosha"
        - name: Telegram
          url: "https://t.me/Groosha"

    homeInfoParams:
        Title: "–î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å!"
        Content: |
          –ú–µ–Ω—è –∑–æ–≤—É—Ç –ê–ª–µ–∫—Å–∞–Ω–¥—Ä, —Ö–æ—Ç—è –º–Ω–æ–≥–∏–µ –º–µ–Ω—è –∑–Ω–∞—é—Ç –ø–æ–¥ –ø—Å–µ–≤–¥–æ–Ω–∏–º–æ–º **–ì—Ä—É—à–∞** (Groosha).
          
          –ù–∏–∂–µ –≤—ã –º–æ–∂–µ—Ç–µ –æ–∑–Ω–∞–∫–æ–º–∏—Ç—å—Å—è —Å –º–æ–∏–º–∏ –ø—Ä–æ–µ–∫—Ç–∞–º–∏ –∏ —Å—Ç—Ä–∞–Ω–∏—Ü–∞–º–∏.

markup:
    goldmark:
        renderer:
            unsafe: true
